title: Typeix - Typescript Node.js Framework 
description: Node.js framework written in typescript which enables javascript developers to use highly-productive development tool made for scaling teams.
theme: jekyll-theme-hacker
